"""likes seeder

Revision ID: 8cc3ac84f3e2
Revises: 2e5e9a84049c
Create Date: 2020-11-29 14:58:32.712584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision = '8cc3ac84f3e2'
down_revision = '2e5e9a84049c'
branch_labels = None
depends_on = None


def upgrade():
    likes = table('likes',
        sa.Column('id', sa.Integer()),
        sa.Column('track_id', sa.Integer()),
        sa.Column('artist_id', sa.Integer())
    )

    op.bulk_insert(likes, [
      {
        'track_id': 1,
        'artist_id': 6
      },
      {
        'track_id': 2,
        'artist_id': 6
      },
      {
        'track_id': 6,
        'artist_id': 6
      },
      {
        'track_id': 7,
        'artist_id': 6
      },
      {
        'track_id': 10,
        'artist_id': 6
      },
      {
        'track_id': 14,
        'artist_id': 6
      },
      {
        'track_id': 19,
        'artist_id': 6
      },
      {
        'track_id': 20,
        'artist_id': 6
      },
      {
        'track_id': 23,
        'artist_id': 6
      },
      {
        'track_id': 24,
        'artist_id': 1
      },
      {
        'track_id': 24,
        'artist_id': 3
      },
      {
        'track_id': 24,
        'artist_id': 5
      },
      {
        'track_id': 1,
        'artist_id': 7
      },
      {
        'track_id': 2,
        'artist_id': 7
      },
      {
        'track_id': 15,
        'artist_id': 7
      },
      {
        'track_id': 16,
        'artist_id': 7
      },
      {
        'track_id': 20,
        'artist_id': 7
      }
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('genres_connector')
    op.drop_table('comments')
    op.drop_table('tracks')
    op.drop_table('transactions')
    op.drop_table('followers')
    op.drop_table('albums')
    op.drop_table('genres')
    op.drop_table('artists')
    # ### end Alembic commands ###
